.\" Manpage for huffman
.TH man 1 "27 August 2015" "1.0" "huffman man page"
.SH NAME
huffman \- encode or decode data using Huffman encoding algorythm
.SH SYNOPSIS
huffman [OPTIONS]
.SH DESCRIPTION
huffman allows to encode and decode input using Huffman encoding algorythm.
.LP
The result of encoding is scheme and binary output, which are separated or binded together, depending on the options.
The result of decoding is data decoded from the input, based on the scheme provided. If scheme input is not specified huffman will try to find it in the begining of the encoded input.
.LP
The scheme has the following format: <[SYMBOL]|[CODE];[SYMBOL]|[CODE]; ... [CODE];/>	Ex. : <a|0;b|1;/>
.LP
Usage Ex. cat input | huffman >> encoded.hf
.LP
	  cat encoded | huffman -d >> output
.LP
('output' will not differ from 'input')
.SH OPTIONS
-h --help Displays help message.
.LP
-i --input [PATH] Input file path. The default is terminal input.
.LP
-d --decode Decode instead of encode.
.LP
-o --output [PATH] Output file path. The default is terminal output.
.LP
-c --clear Separate scheme and coded file
.LP
	-os --output-scheme [PATH] Generated scheme file path. The default is terminal output.
.LP
-s --scheme [PATH] Custom scheme file path
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Igor Kholopov (kholopov96@gmail.com, https://github.com/IKholopov/HuffmanCoding) 
